#baseURL = "https://prisoner7.me/"
languageCode = "ru"
DefaultContentLanguage = "ru"
title = "Prisoner Seven"
#theme = "beautifulhugo"
#theme = "hyde-hyde"
theme = "m10c"
copyright = "Copyleft - All rights are reserved for God"

[Params]
homeTitle = "Заметки"
subtitle = "Open source, фантазии, разное"
author = 'Prisoner7'
description = 'Случайные заметки об Open Source, прочитанных книгах, просмотренных фильмах и продуманных мыслях'
avatar = 'avatar.png'

[[params.social]]


[author]
    name = ""
    github = ""
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

